export const INITIATE_AJAX_REQUEST = 'INITIATE_AJAX_REQUEST';
export const AJAX_REQUEST_ERROR = 'AJAX_REQUEST_ERROR';

export const LOAD_SCHEDULES_SUCCESS = 'LOAD_SCHEDULES_SUCCESS';
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';

export const LOAD_USERS = 'GET_USERS';
export const LOAD_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const LOAD_USER_BY_ID = 'GET_USER_BY_ID';

export const LOAD_TEMPLATES_SUCCESS = 'LOAD_TEMPLATES_SUCCESS';
export const LOAD_SURVEYS_SUCCESS = 'LOAD_SURVEYS_SUCCESS';
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS';

export const GENERATE_REPORT_SUCCESS = 'GENERATE_REPORT_SUCCESS';
