export const INITIATE_AJAX_REQUEST = 'INITIATE_AJAX_REQUEST';
export const AJAX_REQUEST_ERROR = 'AJAX_REQUEST_ERROR';

export const LOAD_SCHEDULES = 'GET_SCHEDULES';
export const LOAD_SCHEDULES_SUCCESS = 'LOAD_SCHEDULES_SUCCESS';
export const GET_SCHEDULE_BY_ID_SUCCESS = 'GET_SCHEDULE_BY_ID_SUCCESS';
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';

export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USER_BY_ID = 'LOAD_USER_BY_ID';

export const LOAD_TEMPLATES_SUCCESS = 'LOAD_TEMPLATES_SUCCESS';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';

export const LOAD_SURVEYS_SUCCESS = 'LOAD_SURVEYS_SUCCESS';
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS';
export const SAVE_SURVEY_RESPONSE_SUCCESS = 'SAVE_SURVEY_RESPONSE_SUCCESS';


export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';

export const GENERATE_REPORT_SUCCESS = 'GENERATE_REPORT_SUCCESS';
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS';
